Repository chiraag-kakar/sharenlearn, pull requests merged in 2021-04, with the labels that each got.

#86 #73 Solved - Recaptcha checkbox in login form.
  myapp/templates/login.html
  myapp/views.py
  mysite/settings.py
  requirements.txt
Labels: Level3, approved, gssoc21

#94 Update README.md
  README.md
Labels: Level1, approved, gssoc21

#97 added required in input
  myapp/templates/signup.html
Labels: Level0, approved, gssoc21

#102 🚀[Feat]: Contact page : UI changed
  myapp/templates/contact.html
  myapp/templates/navigation.html
Labels: gssoc21

#107 Updated Navbar with prevention of Logged in user to visit login page
  myapp/templates/navigation.html
  myapp/templates/usernavigation.html
  myapp/views.py
Labels: Level2, approved, gssoc21

#117 Signup password validation #113
  myapp/views.py
Labels: Level1, approved, gssoc21

#124 Fixed Web-address in Readme.md
  .gitignore
  README.md
Labels: Level0, approved, gssoc21

#133 Forgot Password
  myapp/templates/forgotpassword.html
  myapp/templates/login.html
  myapp/views.py
  mysite/urls.py
Labels: Level2, approved, gssoc21

#134 Dialogflow Chatbot
  myapp/templates/footer.html
Labels: Level3, approved, gssoc21

#125 Show on screen errors or messages instead of js alerts issue: #121
  myapp/templates/admin_nav.html
  myapp/templates/assign_status.html
  myapp/templates/changepassword.html
  myapp/templates/edit_profile.html
  myapp/templates/login.html
  myapp/templates/login_admin.html
  myapp/templates/navigation.html
  myapp/templates/signup.html
  myapp/templates/upload_notes.html
  myapp/templates/usernavigation.html
  myapp/views.py
  mysite/settings.py
Labels: Level2, gssoc21

#166 Signup page bug fix
  myapp/templates/signup.html
Labels: Level2, approved, gssoc21

#169 Otp verification
  myapp/admin.py
  myapp/migrations/0003_otpmodel.py
  myapp/models.py
  myapp/static/js/signup.js
  myapp/templates/emails/otp.html
  myapp/templates/signup.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#135 Added form validaions and success/error message in contact
  myapp/templates/contact.html
  myapp/templates/navigation.html
  myapp/views.py
  mysite/settings.py
Labels: Level2, approved, gssoc21

#190 QA : Added Issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level2, gssoc21

#186 Added preloader
  myapp/templates/navigation.html
Labels: Level2, approved, gssoc21

#185 Fixed Issue #177
  myapp/static/css/mystyle.css
  myapp/templates/contact.html
  myapp/templates/navigation.html
  myvenv/pyvenv.cfg
Labels: Level2, approved, gssoc21

#146 Made table in viewall_usernotes.html responsive as per issue #127
  myapp/templates/viewall_usernotes.html
Labels: Level1, approved, gssoc21

#176 Ajax Validations on Signup and Login
  myapp/static/js/login.js
  myapp/static/js/signup.js
  myapp/templates/login.html
  myapp/templates/signup.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#167 Fixed Admin login and made it responsive
  myapp/static/css/mystyle.css
  myapp/templates/login_admin.html
  myvenv/pyvenv.cfg
Labels: Level2, approved, gssoc21

#148 Solves #141
  myapp/templates/upload_notes.html
Labels: Level1, approved, gssoc21

#187 fixed login form
  myapp/static/css/mystyle.css
  myapp/templates/login.html
  mysite/urls.py
Labels: Level2, approved, gssoc21

#180 Forgot Password with OTP Verification
  myapp/static/js/forgot-pwd.js
  myapp/templates/forgotpassword.html
  myapp/templates/login.html
  myapp/views.py
Labels: Level3, approved, gssoc21
