Repository chiraag-kakar/sharenlearn, pull requests merged in 2021-05, with the labels that each got.

#192 UI Enhancements for Home Page
  .gitignore
  myapp/static/css/styles.css
  myapp/static/images/favicon.png
  myapp/static/images/icon-facebook.svg
  myapp/static/images/icon-hamburger.svg
  myapp/static/images/icon-instagram.svg
  myapp/static/images/icon-twitter.svg
  myapp/static/images/illustration-learn.svg
  myapp/static/images/illustration-phone.svg
  myapp/static/images/instagram.png
  myapp/static/images/logo.svg
  myapp/static/js/scripts.js
  myapp/templates/base.html
  myapp/templates/footer1.html
  myapp/templates/header.html
  myapp/templates/home.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#205 UI Enhancements for Login Page
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/base.html
  myapp/templates/login.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#209 UI Enhancements for Contact Page
  myapp/static/css/styles.css
  myapp/static/images/illustration-contact.svg
  myapp/static/js/scripts.js
  myapp/templates/contact.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#217 UI Enhancements for Edit Profile Page
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/edit_profile.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#204 Update README.md
  README.md
Labels: Level0, approved, gssoc21

#221 UI Enhancements for Upload Form Page
  myapp/static/css/styles.css
  myapp/static/images/icon-folder.svg
  myapp/static/js/scripts.js
  myapp/templates/upload_notes.html
  myapp/templates/view_usernotes.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#222 Refactor Home UI (Home, About, Contact in one Page)
  myapp/static/css/styles.css
  myapp/static/images/icon-essence.svg
  myapp/static/images/icon-goal.svg
  myapp/static/images/icon-team.svg
  myapp/templates/about.html
  myapp/templates/contact.html
  myapp/templates/header.html
  myapp/templates/home.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#244 Update footer
  myapp/static/css/styles.css
  myapp/static/images/icon-facebook.svg
  myapp/static/images/icon-github.svg
  myapp/static/images/icon-instagram.svg
  myapp/static/images/icon-twitter.svg
  myapp/templates/footer1.html
Labels: Level3, approved, gssoc21

#247 Implement Search Feature (For Admin Page)
  myapp/static/css/styles.css
  myapp/static/images/icon-approved.svg
  myapp/static/images/icon-cross-red.svg
  myapp/static/images/icon-instagram.svg
  myapp/static/images/icon-search.svg
  myapp/static/images/icon-twitter.svg
  myapp/static/js/scripts.js
  myapp/templates/admin_dashboard.html
Labels: Level3, approved, gssoc21

#248 UI Enhancements for Super Admin Page
  myapp/static/css/styles.css
  myapp/static/images/icon-admin-bw.svg
  myapp/static/images/icon-staff-bw.svg
  myapp/static/images/icon-user-bw.svg
  myapp/static/js/scripts.js
  myapp/templates/header.html
  myapp/templates/profile.html
  myapp/templates/superadmin_dashboard.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#250 Update Confirmation Logout Alert Box
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/header.html
Labels: Level3, approved, gssoc21

#256 Email authentication
  myapp/static/js/scripts.js
  myapp/templates/login.html
  myapp/views.py
  mysite/urls.py
  requirements.txt
Labels: Level3, approved, gssoc21

#258 Added a Sign Up button
  myapp/templates/header.html
Labels: Level1, approved, gssoc21

#260 Fix captcha issue
  myapp/static/js/scripts.js
  myapp/views.py
Labels: Level2, approved, gssoc21

#263 UI for Change Password Page
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/change_password.html
  myapp/templates/edit_profile.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#265 Implement Email Authentication in Change Password Page
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/edit_profile.html
  myapp/templates/header.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#267 Account Activated/Link Expired Page UI
  myapp/static/css/styles.css
  myapp/static/images/icon-auth.svg
  myapp/static/js/scripts.js
  myapp/templates/auth_page.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#269 Fix Super User Profile Page Issue
  myapp/templates/header.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#271 Design HTML email templates
  myapp/templates/emails/mail_template.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#272 Adding Top-button
  myapp/static/css/styles.css
  myapp/templates/footer1.html
Labels: Level2, gssoc21

#274 Update contact form
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/contact.html
  myapp/templates/footer1.html
  myapp/templates/home.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#277 Password Reset Code and Password Changed HTML Email Templates
  myapp/templates/emails/mail_template.html
  myapp/views.py
Labels: Level3, approved, gssoc21

#283 Using svg instead of icons
  myapp/static/css/styles.css
  myapp/static/images/icon-eye.svg
  myapp/static/images/icon-top-btn.svg
  myapp/static/js/scripts.js
  myapp/templates/change_password.html
  myapp/templates/footer1.html
  myapp/templates/forgot_password.html
  myapp/templates/login.html
  myapp/templates/signup.html
Labels: Level2, approved, gssoc21

#285 Fix UI issues
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/admin_dashboard.html
  myapp/templates/base.html
  myapp/templates/header.html
Labels: Level2, approved, gssoc21

#286 New README Banner
  New-Banner.png
  README.md
Labels: Level1, approved, gssoc21

#294 Update readme.md
  README.md
  banner.svg
Labels: Level2, approved, gssoc21

#303 Reactions Feature (Like/Dislike)
  myapp/migrations/0001_initial.py
  myapp/migrations/0002_notes_likes.py
  myapp/migrations/0003_auto_20210531_1716.py
  myapp/migrations/0004_notes_dislikes.py
  myapp/migrations/__init__.py
  myapp/models.py
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
  myapp/templates/view_note.html
  myapp/templates/viewall_usernotes.html
  myapp/views.py
  mysite/urls.py
Labels: Level3, approved, gssoc21

#305 Update scrollbar
  myapp/static/css/styles.css
  myapp/static/js/scripts.js
Labels: Level2, approved, gssoc21

#307 Delete note functionality
  myapp/static/css/styles.css
  myapp/templates/view_note.html
  myapp/views.py
Labels: Level2, approved, gssoc21
